name: vista
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - rasterio
  - pyproj
  - numpy
  - matplotlib
  - requests
  - python-dateutil
  - shapely
  - scikit-learn
  - geopandas
  - osmnx
  - lark
  - pillow
  - PySide6
  - psutil
  - OpenEXR