"""Visualization of SurveyObservabilityField spatial products.

This module provides reusable Matplotlib visualizations for the principal
spatial products generated by Rivelero's SurveyObservabilityField (SOF).

The visualization layer is intentionally separate from observability
calculation. Functions in this module:

- do not calculate viewsheds;
- do not modify the SOF;
- do not calculate exposure;
- do not implement survey metrics;
- do not depend on the GUI.

They consume already-derived SOF products and return ordinary Matplotlib
Figure and Axes objects so that the same visualization functions can be used
in scripts, notebooks, documentation, tests, and the future Rivelero GUI.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
from matplotlib.colors import BoundaryNorm, Colormap, ListedColormap
from matplotlib.figure import Figure
from matplotlib.patches import Patch

from rivelero.observability.masks import ObservabilityState

if TYPE_CHECKING:
    from rivelero.observability.survey_field import (
        SurveyObservabilityField,
    )


# ---------------------------------------------------------------------------
# Shared observability colour semantics
# ---------------------------------------------------------------------------

# Categorical state colours, indexed by ObservabilityState. Blind spot
# (orange) and observable (blue) replace an earlier red/green pair whose
# OKLab separation under deuteranopia was only 3.4; every pair below stays
# above 11 under simulated protan/deutan/tritan vision.
OBSERVABILITY_STATE_COLORS: dict[ObservabilityState, str] = {
    ObservabilityState.OUTSIDE_DOMAIN: "#F2F2F2",
    ObservabilityState.INVALID: "#6E6E6E",
    ObservabilityState.BLIND_SPOT: "#E07B39",
    ObservabilityState.OBSERVABLE: "#2A78D6",
}

OBSERVABILITY_STATE_LABELS: dict[ObservabilityState, str] = {
    ObservabilityState.OUTSIDE_DOMAIN: "Outside domain",
    ObservabilityState.INVALID: "Invalid / unanalysable",
    ObservabilityState.BLIND_SPOT: "Blind spot",
    ObservabilityState.OBSERVABLE: "Observable",
}

# Neutral context for analysable cells that are not the highlighted class.
CONTEXT_COLOR = "#D9D9D9"

# Single-hue light-to-dark ramp for continuous exposure quantities. The ramp
# starts at a visible pale blue so that zero exposure (a blind spot) is not
# confused with the white surface or with cells that carry no value.
EXPOSURE_CMAP = ListedColormap(
    plt.get_cmap("Blues")(np.linspace(0.15, 1.0, 256)),
    name="rivelero_exposure",
)


def observability_state_colormap() -> tuple[ListedColormap, BoundaryNorm]:
    """Return the fixed categorical colormap and norm for state rasters."""

    cmap = ListedColormap(
        [
            OBSERVABILITY_STATE_COLORS[state]
            for state in ObservabilityState
        ],
        name="rivelero_observability_state",
    )

    norm = BoundaryNorm(
        np.arange(len(ObservabilityState) + 1, dtype=float) - 0.5,
        cmap.N,
    )

    return cmap, norm


def observability_state_legend_handles() -> list[Patch]:
    """Return legend patches for every categorical observability state."""

    return [
        Patch(
            facecolor=OBSERVABILITY_STATE_COLORS[state],
            edgecolor="#8A9297",
            label=OBSERVABILITY_STATE_LABELS[state],
        )
        for state in ObservabilityState
    ]


# ---------------------------------------------------------------------------
# Public visualization functions
# ---------------------------------------------------------------------------


def plot_exposure(
    sof: "SurveyObservabilityField",
    *,
    ax: Axes | None = None,
    title: str = "Visual exposure",
    cmap: str | Colormap = EXPOSURE_CMAP,
    show_colorbar: bool = True,
    mask_nonanalysable: bool = True,
) -> tuple[Figure, Axes]:
    """Plot cumulative visual exposure.

    Parameters
    ----------
    sof
        SurveyObservabilityField to visualize.

    ax
        Optional Matplotlib Axes. If omitted, a new Figure and Axes are
        created.

    title
        Figure title.

    cmap
        Matplotlib colormap used for exposure values.

    show_colorbar
        Whether to display a colorbar.

    mask_nonanalysable
        If True, cells outside analysable space are hidden rather than shown
        as zero exposure.

    Returns
    -------
    tuple[Figure, Axes]
        Matplotlib Figure and Axes containing the visualization.

    Notes
    -----
    Exposure count represents the number of active sampling units from which
    each cell was visible.

    Zero exposure within analysable space therefore represents a blind spot,
    whereas cells outside analysable space have no valid exposure
    interpretation.
    """

    _validate_sof(sof)

    fig, ax = _prepare_axes(ax)

    data = sof.exposure_count.astype(
        np.float64,
        copy=True,
    )

    if mask_nonanalysable:
        data = np.ma.masked_where(
            ~sof.analysable_mask,
            data,
        )

    image = ax.imshow(
        data,
        extent=_raster_extent(sof),
        origin="upper",
        cmap=cmap,
        interpolation="nearest",
        vmin=0,
    )

    ax.set_title(title)

    _format_spatial_axes(
        ax,
        sof,
    )

    if show_colorbar:
        colorbar = fig.colorbar(
            image,
            ax=ax,
            fraction=0.046,
            pad=0.04,
        )

        colorbar.set_label(
            "Exposure count (sampling units)"
        )

    return fig, ax


def plot_normalized_exposure(
    sof: "SurveyObservabilityField",
    *,
    ax: Axes | None = None,
    title: str = "Normalized visual exposure",
    cmap: str | Colormap = EXPOSURE_CMAP,
    show_colorbar: bool = True,
    mask_nonanalysable: bool = True,
) -> tuple[Figure, Axes]:
    """Plot globally normalized exposure.

    Parameters
    ----------
    sof
        SurveyObservabilityField to visualize.

    ax
        Optional Matplotlib Axes.

    title
        Figure title.

    cmap
        Matplotlib colormap.

    show_colorbar
        Whether to display a colorbar.

    mask_nonanalysable
        Whether cells outside analysable space should be hidden.

    Returns
    -------
    tuple[Figure, Axes]
        Matplotlib Figure and Axes.

    Notes
    -----
    The current Rivelero normalized-exposure product is:

        exposure_count / number_of_active_sampling_units

    This is a global normalization and should not be interpreted as the
    future eligibility-normalized exposure metric.
    """

    _validate_sof(sof)

    fig, ax = _prepare_axes(ax)

    data = sof.normalized_exposure.astype(
        np.float64,
        copy=True,
    )

    if mask_nonanalysable:
        data = np.ma.masked_where(
            ~sof.analysable_mask,
            data,
        )

    image = ax.imshow(
        data,
        extent=_raster_extent(sof),
        origin="upper",
        cmap=cmap,
        interpolation="nearest",
        vmin=0.0,
        vmax=1.0,
    )

    ax.set_title(title)

    _format_spatial_axes(
        ax,
        sof,
    )

    if show_colorbar:
        colorbar = fig.colorbar(
            image,
            ax=ax,
            fraction=0.046,
            pad=0.04,
        )

        colorbar.set_label(
            "Normalized exposure"
        )

    return fig, ax


def plot_observability_state(
    sof: "SurveyObservabilityField",
    *,
    ax: Axes | None = None,
    title: str = "Observability state",
    show_legend: bool = True,
) -> tuple[Figure, Axes]:
    """Plot the categorical observability state of the analysis domain.

    The four Rivelero states are:

        0 = outside analysis domain
        1 = invalid / unanalysable
        2 = blind spot
        3 = observable

    Parameters
    ----------
    sof
        SurveyObservabilityField to visualize.

    ax
        Optional Matplotlib Axes.

    title
        Figure title.

    show_legend
        Whether to display the categorical-state legend.

    Returns
    -------
    tuple[Figure, Axes]
        Matplotlib Figure and Axes.

    Notes
    -----
    This visualization preserves a central Rivelero distinction:

    a cell with no reconstructed exposure is only a blind spot when that
    cell belongs to the valid analysable domain.
    """

    _validate_sof(sof)

    fig, ax = _prepare_axes(ax)

    state = sof.observability_state

    # Fixed categorical colors are appropriate here because these values are
    # discrete semantic states rather than a continuous quantitative field.
    cmap, norm = observability_state_colormap()

    ax.imshow(
        state,
        extent=_raster_extent(sof),
        origin="upper",
        cmap=cmap,
        norm=norm,
        interpolation="nearest",
    )

    ax.set_title(title)

    _format_spatial_axes(
        ax,
        sof,
    )

    if show_legend:
        ax.legend(
            handles=observability_state_legend_handles(),
            title="Observability state",
            loc="upper right",
            frameon=True,
        )

    return fig, ax


def plot_blindspots(
    sof: "SurveyObservabilityField",
    *,
    ax: Axes | None = None,
    title: str = "Survey blind spots",
    show_observable_context: bool = True,
    show_legend: bool = True,
) -> tuple[Figure, Axes]:
    """Highlight blind spots within analysable space.

    Parameters
    ----------
    sof
        SurveyObservabilityField to visualize.

    ax
        Optional Matplotlib Axes.

    title
        Figure title.

    show_observable_context
        If True, observable cells are shown as contextual background.
        If False, only blind-spot cells are displayed.

    show_legend
        Whether to show a legend.

    Returns
    -------
    tuple[Figure, Axes]
        Matplotlib Figure and Axes.

    Notes
    -----
    Invalid and outside-domain cells are not classified as blind spots.
    """

    _validate_sof(sof)

    fig, ax = _prepare_axes(ax)

    extent = _raster_extent(
        sof
    )

    if show_observable_context:
        context = np.ma.masked_where(
            ~sof.observable_mask,
            np.ones(
                sof.exposure_count.shape,
                dtype=np.uint8,
            ),
        )

        observable_cmap = ListedColormap(
            [CONTEXT_COLOR]
        )

        ax.imshow(
            context,
            extent=extent,
            origin="upper",
            cmap=observable_cmap,
            interpolation="nearest",
            vmin=0,
            vmax=1,
        )

    blind = np.ma.masked_where(
        ~sof.blindspot_mask,
        np.ones(
            sof.exposure_count.shape,
            dtype=np.uint8,
        ),
    )

    blind_cmap = ListedColormap(
        [OBSERVABILITY_STATE_COLORS[
            ObservabilityState.BLIND_SPOT
        ]]
    )

    ax.imshow(
        blind,
        extent=extent,
        origin="upper",
        cmap=blind_cmap,
        interpolation="nearest",
        vmin=0,
        vmax=1,
    )

    ax.set_title(title)

    _format_spatial_axes(
        ax,
        sof,
    )

    if show_legend:
        handles = []

        if show_observable_context:
            handles.append(
                Patch(
                    facecolor=CONTEXT_COLOR,
                    label="Observable",
                )
            )

        handles.append(
            Patch(
                facecolor=OBSERVABILITY_STATE_COLORS[
            ObservabilityState.BLIND_SPOT
        ],
                label="Blind spot",
            )
        )

        ax.legend(
            handles=handles,
            loc="upper right",
            frameon=True,
        )

    return fig, ax


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _prepare_axes(
    ax: Axes | None,
) -> tuple[Figure, Axes]:
    """Return a Figure/Axes pair."""

    if ax is None:
        fig, new_ax = plt.subplots(
            figsize=(8, 7)
        )

        return fig, new_ax

    if not isinstance(
        ax,
        Axes,
    ):
        raise TypeError(
            "ax must be a matplotlib.axes.Axes or None."
        )

    return ax.figure, ax


def _raster_extent(
    sof: "SurveyObservabilityField",
) -> tuple[
    float,
    float,
    float,
    float,
]:
    """Return Matplotlib extent from the SOF affine transform.

    Returns
    -------
    tuple
        ``(left, right, bottom, top)``

    Notes
    -----
    This helper supports general affine transforms by evaluating the four
    outer raster corners rather than assuming a north-up raster.
    """

    rows, cols = (
        sof.exposure_count.shape
    )

    transform = sof.transform

    corners = (
        transform * (0, 0),
        transform * (cols, 0),
        transform * (0, rows),
        transform * (cols, rows),
    )

    xs = [
        point[0]
        for point in corners
    ]

    ys = [
        point[1]
        for point in corners
    ]

    return (
        float(min(xs)),
        float(max(xs)),
        float(min(ys)),
        float(max(ys)),
    )


def _format_spatial_axes(
    ax: Axes,
    sof: "SurveyObservabilityField",
) -> None:
    """Apply common spatial-axis formatting."""

    ax.set_aspect(
        "equal"
    )

    crs = sof.crs

    if (
        crs is not None
        and crs.is_projected
    ):
        unit_name = _crs_linear_unit_name(
            crs
        )

        if unit_name:
            ax.set_xlabel(
                f"X ({unit_name})"
            )
            ax.set_ylabel(
                f"Y ({unit_name})"
            )
        else:
            ax.set_xlabel(
                "X"
            )
            ax.set_ylabel(
                "Y"
            )

    else:
        ax.set_xlabel(
            "X"
        )
        ax.set_ylabel(
            "Y"
        )

    ax.ticklabel_format(
        style="plain",
        useOffset=False,
        axis="both",
    )


def _crs_linear_unit_name(
    crs,
) -> str | None:
    """Return a readable linear unit name for a projected CRS."""

    try:
        units = crs.linear_units
    except AttributeError:
        return None

    if units is None:
        return None

    value = str(
        units
    ).strip()

    if not value:
        return None

    if value.lower() in {
        "metre",
        "meter",
        "metres",
        "meters",
        "m",
    }:
        return "m"

    return value


def _validate_sof(
    sof: "SurveyObservabilityField",
) -> None:
    """Perform lightweight validation of the visualization input.

    The import is local to avoid introducing an unnecessary import cycle
    during module initialization.
    """

    from rivelero.observability.survey_field import (
        SurveyObservabilityField,
    )

    if not isinstance(
        sof,
        SurveyObservabilityField,
    ):
        raise TypeError(
            "sof must be a SurveyObservabilityField."
        )

    expected_shape = (
        sof.exposure_count.shape
    )

    for name in (
        "analysis_mask",
        "valid_mask",
    ):
        value = getattr(
            sof,
            name,
        )

        if value.shape != expected_shape:
            raise ValueError(
                f"{name} shape does not match exposure_count."
            )