"""Exposure calculations for Rivelero.

This module contains reusable mathematical operations for deriving and
updating spatial exposure products from visibility masks.

Exposure describes the spatial distribution of visual observation
opportunity generated by a collection of Viewpoints or ObservationEvents.

The functions in this module operate only on NumPy arrays. They do not
manage SurveyObservabilityField state, visibility storage, viewpoint
metadata, or viewshed calculation.
"""

from __future__ import annotations

from collections.abc import Iterable

import numpy as np


# ---------------------------------------------------------------------------
# Exposure-count construction
# ---------------------------------------------------------------------------


def exposure_count_from_masks(
    visibility_masks: Iterable[np.ndarray],
    *,
    analysable_mask: np.ndarray | None = None,
    dtype: np.dtype | type = np.uint32,
) -> np.ndarray:
    """Calculate cumulative exposure from multiple visibility masks.

    Parameters
    ----------
    visibility_masks
        Iterable of two-dimensional boolean or binary visibility masks.
        Each mask represents one Viewpoint or ObservationEvent.

    analysable_mask
        Optional boolean mask defining cells that legitimately participate
        in the analysis. Cells outside this mask receive zero exposure.

    dtype
        Unsigned integer dtype used for the exposure-count raster.

    Returns
    -------
    numpy.ndarray
        Integer raster containing the number of supplied visibility masks
        from which each cell is visible.

    Notes
    -----
    Large Rivelero analyses should normally update a
    SurveyObservabilityField incrementally rather than loading every
    visibility mask into RAM simultaneously.
    """

    dtype = _validate_exposure_dtype(
        dtype
    )

    iterator = iter(
        visibility_masks
    )

    try:
        first = next(
            iterator
        )
    except StopIteration as exc:
        raise ValueError(
            "visibility_masks must contain at least one mask."
        ) from exc

    first_mask = _as_boolean_mask(
        "visibility_mask",
        first,
    )

    shape = first_mask.shape

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=shape,
    )

    exposure = np.zeros(
        shape,
        dtype=dtype,
    )

    _increment_exposure(
        exposure,
        first_mask & valid,
    )

    for mask in iterator:

        current = _as_boolean_mask(
            "visibility_mask",
            mask,
        )

        if current.shape != shape:
            raise ValueError(
                "All visibility masks must have the same shape."
            )

        _increment_exposure(
            exposure,
            current & valid,
        )

    exposure[
        ~valid
    ] = 0

    return exposure


# ---------------------------------------------------------------------------
# Incremental exposure modification
# ---------------------------------------------------------------------------


def add_visibility_to_exposure(
    exposure_count: np.ndarray,
    visibility_mask: np.ndarray,
    *,
    analysable_mask: np.ndarray | None = None,
    inplace: bool = False,
) -> np.ndarray:
    """Add one visibility contribution to an exposure-count raster.

    Parameters
    ----------
    exposure_count
        Existing non-negative integer exposure raster.

    visibility_mask
        Visibility mask to add.

    analysable_mask
        Optional mask restricting which cells may receive exposure.

    inplace
        If True, modify exposure_count directly. Otherwise return an
        independent updated copy.

    Returns
    -------
    numpy.ndarray
        Updated exposure-count raster.
    """

    exposure = _validate_exposure_count(
        exposure_count,
        copy=not inplace,
    )

    visibility = _as_boolean_mask(
        "visibility_mask",
        visibility_mask,
    )

    if (
        visibility.shape
        != exposure.shape
    ):
        raise ValueError(
            "visibility_mask and exposure_count must have "
            "the same shape."
        )

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=exposure.shape,
    )

    contribution = (
        visibility
        & valid
    )

    _increment_exposure(
        exposure,
        contribution,
    )

    exposure[
        ~valid
    ] = 0

    return exposure


def remove_visibility_from_exposure(
    exposure_count: np.ndarray,
    visibility_mask: np.ndarray,
    *,
    analysable_mask: np.ndarray | None = None,
    inplace: bool = False,
) -> np.ndarray:
    """Remove one visibility contribution from an exposure-count raster.

    Parameters
    ----------
    exposure_count
        Existing non-negative integer exposure raster.

    visibility_mask
        Visibility mask whose contribution should be removed.

    analysable_mask
        Optional mask restricting the analysis.

    inplace
        If True, modify exposure_count directly.

    Returns
    -------
    numpy.ndarray
        Updated exposure-count raster.

    Raises
    ------
    ValueError
        If removal would produce negative exposure.
    """

    exposure = _validate_exposure_count(
        exposure_count,
        copy=not inplace,
    )

    visibility = _as_boolean_mask(
        "visibility_mask",
        visibility_mask,
    )

    if (
        visibility.shape
        != exposure.shape
    ):
        raise ValueError(
            "visibility_mask and exposure_count must have "
            "the same shape."
        )

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=exposure.shape,
    )

    contribution = (
        visibility
        & valid
    )

    if np.any(
        exposure[
            contribution
        ] == 0
    ):
        raise ValueError(
            "Cannot remove visibility contribution because "
            "one or more affected cells currently have zero exposure."
        )

    exposure[
        contribution
    ] -= 1

    exposure[
        ~valid
    ] = 0

    return exposure


# ---------------------------------------------------------------------------
# Exposure normalization
# ---------------------------------------------------------------------------


def normalize_exposure_global(
    exposure_count: np.ndarray,
    n_sampling_units: int,
    *,
    analysable_mask: np.ndarray | None = None,
    dtype: np.dtype | type = np.float32,
) -> np.ndarray:
    """Normalize exposure by the total number of sampling units.

    The calculation is:

        normalized_exposure(x)
            = exposure_count(x) / n_sampling_units

    This is the initial global Rivelero normalization. It should not be
    confused with future eligibility-aware normalization.
    """

    exposure = _validate_exposure_count(
        exposure_count,
        copy=False,
    )

    if not isinstance(
        n_sampling_units,
        int,
    ):
        raise TypeError(
            "n_sampling_units must be an integer."
        )

    if n_sampling_units < 0:
        raise ValueError(
            "n_sampling_units must be greater than or equal to zero."
        )

    output_dtype = np.dtype(
        dtype
    )

    if not np.issubdtype(
        output_dtype,
        np.floating,
    ):
        raise TypeError(
            "Normalized exposure dtype must be floating point."
        )

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=exposure.shape,
    )

    result = np.zeros(
        exposure.shape,
        dtype=output_dtype,
    )

    if n_sampling_units == 0:

        if np.any(
            exposure > 0
        ):
            raise ValueError(
                "Exposure is non-zero but n_sampling_units is zero."
            )

        return result

    if np.any(
        exposure > n_sampling_units
    ):
        raise ValueError(
            "exposure_count cannot exceed n_sampling_units "
            "when using global normalization."
        )

    np.divide(
        exposure,
        float(
            n_sampling_units
        ),
        out=result,
        where=valid,
    )

    result[
        ~valid
    ] = 0.0

    return result


def normalize_exposure_by_eligibility(
    exposure_count: np.ndarray,
    eligible_count: np.ndarray,
    *,
    analysable_mask: np.ndarray | None = None,
    dtype: np.dtype | type = np.float32,
) -> np.ndarray:
    """Normalize exposure by cell-specific observation opportunity.

    Parameters
    ----------
    exposure_count
        Number of sampling units that actually contribute visibility
        to each cell.

    eligible_count
        Number of sampling units considered eligible to observe each
        cell under an externally defined eligibility rule.

    analysable_mask
        Optional boolean mask defining analysable cells.

    dtype
        Floating-point dtype of the result.

    Notes
    -----
    This function provides the mathematical operation required for future
    eligibility-aware exposure normalization.

    It deliberately does not define what makes a Viewpoint eligible to
    observe a cell.
    """

    exposure = _validate_exposure_count(
        exposure_count,
        copy=False,
    )

    eligible = _validate_exposure_count(
        eligible_count,
        copy=False,
        name="eligible_count",
    )

    if (
        exposure.shape
        != eligible.shape
    ):
        raise ValueError(
            "exposure_count and eligible_count must have "
            "the same shape."
        )

    if np.any(
        exposure > eligible
    ):
        raise ValueError(
            "exposure_count cannot exceed eligible_count."
        )

    output_dtype = np.dtype(
        dtype
    )

    if not np.issubdtype(
        output_dtype,
        np.floating,
    ):
        raise TypeError(
            "Normalized exposure dtype must be floating point."
        )

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=exposure.shape,
    )

    denominator_valid = (
        valid
        & (eligible > 0)
    )

    result = np.zeros(
        exposure.shape,
        dtype=output_dtype,
    )

    np.divide(
        exposure,
        eligible,
        out=result,
        where=denominator_valid,
    )

    result[
        ~valid
    ] = 0.0

    return result


# ---------------------------------------------------------------------------
# Observation-opportunity support
# ---------------------------------------------------------------------------


def opportunity_count_from_masks(
    opportunity_masks: Iterable[np.ndarray],
    *,
    analysable_mask: np.ndarray | None = None,
    dtype: np.dtype | type = np.uint32,
) -> np.ndarray:
    """Count cell-specific observation opportunities.

    This is mathematically identical to cumulative exposure, but its
    semantic meaning differs.

    Each supplied mask represents whether a sampling unit was eligible
    to observe a cell rather than whether the cell was actually visible.
    """

    return exposure_count_from_masks(
        opportunity_masks,
        analysable_mask=analysable_mask,
        dtype=dtype,
    )


# ---------------------------------------------------------------------------
# Exposure summaries
# ---------------------------------------------------------------------------


def maximum_exposure(
    exposure_count: np.ndarray,
    *,
    analysable_mask: np.ndarray | None = None,
) -> int:
    """Return maximum exposure among analysable cells."""

    exposure = _validate_exposure_count(
        exposure_count,
        copy=False,
    )

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=exposure.shape,
    )

    if not np.any(
        valid
    ):
        return 0

    return int(
        np.max(
            exposure[
                valid
            ]
        )
    )


def total_exposure(
    exposure_count: np.ndarray,
    *,
    analysable_mask: np.ndarray | None = None,
) -> int:
    """Return total viewpoint-cell visibility relationships."""

    exposure = _validate_exposure_count(
        exposure_count,
        copy=False,
    )

    valid = _prepare_analysable_mask(
        analysable_mask,
        shape=exposure.shape,
    )

    return int(
        np.sum(
            exposure[
                valid
            ],
            dtype=np.uint64,
        )
    )


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------


def _validate_exposure_count(
    exposure_count: np.ndarray,
    *,
    copy: bool,
    name: str = "exposure_count",
) -> np.ndarray:
    """Validate a non-negative integer exposure raster."""

    if not isinstance(
        exposure_count,
        np.ndarray,
    ):
        raise TypeError(
            f"{name} must be a numpy.ndarray."
        )

    if exposure_count.ndim != 2:
        raise ValueError(
            f"{name} must be two-dimensional."
        )

    if not np.issubdtype(
        exposure_count.dtype,
        np.integer,
    ):
        raise TypeError(
            f"{name} must use an integer dtype."
        )

    if np.any(
        exposure_count < 0
    ):
        raise ValueError(
            f"{name} cannot contain negative values."
        )

    if copy:
        return exposure_count.copy()

    return exposure_count


def _prepare_analysable_mask(
    analysable_mask: np.ndarray | None,
    *,
    shape: tuple[int, int],
) -> np.ndarray:
    """Return a validated analysable-space mask."""

    if analysable_mask is None:
        return np.ones(
            shape,
            dtype=bool,
        )

    valid = _as_boolean_mask(
        "analysable_mask",
        analysable_mask,
    )

    if valid.shape != shape:
        raise ValueError(
            "analysable_mask does not match the "
            "exposure raster shape."
        )

    return valid


def _as_boolean_mask(
    name: str,
    mask: np.ndarray,
) -> np.ndarray:
    """Validate a two-dimensional mask and return boolean form."""

    if not isinstance(
        mask,
        np.ndarray,
    ):
        raise TypeError(
            f"{name} must be a numpy.ndarray."
        )

    if mask.ndim != 2:
        raise ValueError(
            f"{name} must be two-dimensional."
        )

    return mask.astype(
        bool,
        copy=False,
    )


def _validate_exposure_dtype(
    dtype: np.dtype | type,
) -> np.dtype:
    """Validate the dtype used for cumulative exposure."""

    result = np.dtype(
        dtype
    )

    if not np.issubdtype(
        result,
        np.unsignedinteger,
    ):
        raise TypeError(
            "Exposure dtype must be an unsigned integer dtype."
        )

    return result


def _increment_exposure(
    exposure_count: np.ndarray,
    contribution_mask: np.ndarray,
) -> None:
    """Increment exposure while preventing integer overflow."""

    if not np.any(
        contribution_mask
    ):
        return

    maximum = np.iinfo(
        exposure_count.dtype
    ).max

    if np.any(
        exposure_count[
            contribution_mask
        ] >= maximum
    ):
        raise OverflowError(
            "Exposure-count dtype cannot represent "
            "another contribution."
        )

    exposure_count[
        contribution_mask
    ] += 1