"""Survey Observability Field for Rivelero.

A SurveyObservabilityField (SOF) represents the collective spatial
observation opportunity generated by a specified ViewpointConfiguration
within an Environment and AnalysisDomain under a VisibilityConfiguration.

The SOF does not store all individual viewsheds in memory. Individual
viewpoint/event visibility relationships are managed by VisibilityStore.

Instead, the SOF maintains lightweight survey-level state, particularly the
cumulative exposure raster and the identities of the sampling units currently
contributing to it.

Exposure mathematics is implemented in ``rivelero.observability.exposure``.
This class manages the state and provenance of a particular survey.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterable

import numpy as np
from affine import Affine
from rasterio.crs import CRS

from rivelero.core.configuration import ViewpointConfiguration
from rivelero.core.domain import AnalysisDomain
from rivelero.core.environment import Environment
from rivelero.observability.exposure import (
    add_visibility_to_exposure,
    normalize_exposure_global,
    remove_visibility_from_exposure,
)
from rivelero.observability.storage import (
    StoredVisibility,
    VisibilityKey,
    VisibilityStore,
)
from rivelero.visibility.configuration import (
    SamplingUnit,
    VisibilityConfiguration,
)


@dataclass(slots=True)
class SurveyObservabilityField:
    """Collective observability generated by one survey configuration.

    Parameters
    ----------
    sof_id
        Unique identifier for this SurveyObservabilityField.

    viewpoint_configuration_id
        Identifier of the ViewpointConfiguration represented by the SOF.

    environment_id
        Identifier of the Environment used for visibility analysis.

    analysis_domain_id
        Identifier of the AnalysisDomain.

    visibility_configuration_id
        Identifier of the VisibilityConfiguration.

    sampling_unit
        Whether the SOF represents unique Viewpoints or individual
        ObservationEvents.

    exposure_count
        Integer raster containing the number of active sampling units from
        which each analysable cell is visible.

    analysable_mask
        Boolean raster defining cells that legitimately participate in the
        observability analysis.

    transform, crs
        Spatial definition of the SOF raster.

    active_keys
        VisibilityKeys currently contributing to ``exposure_count``.

    created_at
        Time at which the SOF was created.

    metadata
        Additional provenance or processing information.

    Notes
    -----
    Individual visibility masks are intentionally not stored inside this
    object. They are retrieved from VisibilityStore when required.

    The SOF can therefore remain relatively lightweight even when the
    ViewpointConfiguration contains thousands of viewpoints.
    """

    sof_id: str

    viewpoint_configuration_id: str
    environment_id: str
    analysis_domain_id: str
    visibility_configuration_id: str

    sampling_unit: SamplingUnit | str

    exposure_count: np.ndarray
    analysable_mask: np.ndarray

    transform: Affine
    crs: CRS

    active_keys: list[VisibilityKey] = field(default_factory=list)

    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate SOF state."""

        self.sof_id = self._required_string(
            "sof_id",
            self.sof_id,
        )

        for name in (
            "viewpoint_configuration_id",
            "environment_id",
            "analysis_domain_id",
            "visibility_configuration_id",
        ):
            setattr(
                self,
                name,
                self._required_string(
                    name,
                    getattr(self, name),
                ),
            )

        if isinstance(self.sampling_unit, str):
            try:
                self.sampling_unit = SamplingUnit(
                    self.sampling_unit.strip().lower()
                )
            except ValueError as exc:
                raise ValueError(
                    "sampling_unit must be 'viewpoint' or "
                    "'observation_event'."
                ) from exc

        if not isinstance(self.exposure_count, np.ndarray):
            raise TypeError(
                "exposure_count must be a numpy.ndarray."
            )

        if self.exposure_count.ndim != 2:
            raise ValueError(
                "exposure_count must be two-dimensional."
            )

        if not np.issubdtype(
            self.exposure_count.dtype,
            np.integer,
        ):
            raise TypeError(
                "exposure_count must use an integer dtype."
            )

        if np.any(self.exposure_count < 0):
            raise ValueError(
                "exposure_count cannot contain negative values."
            )

        if not isinstance(self.analysable_mask, np.ndarray):
            raise TypeError(
                "analysable_mask must be a numpy.ndarray."
            )

        if self.analysable_mask.ndim != 2:
            raise ValueError(
                "analysable_mask must be two-dimensional."
            )

        self.analysable_mask = self.analysable_mask.astype(
            bool,
            copy=False,
        )

        if self.exposure_count.shape != self.analysable_mask.shape:
            raise ValueError(
                "exposure_count and analysable_mask must have "
                "the same shape."
            )

        if not isinstance(self.transform, Affine):
            raise TypeError("transform must be an Affine.")

        if not isinstance(self.crs, CRS):
            self.crs = CRS.from_user_input(self.crs)

        if not isinstance(self.active_keys, list):
            self.active_keys = list(self.active_keys)

        self._validate_active_keys()

        if not isinstance(self.created_at, datetime):
            raise TypeError(
                "created_at must be a datetime object."
            )

        if not isinstance(self.metadata, dict):
            raise TypeError(
                "metadata must be a dictionary."
            )

        # Exposure outside analysable space has no valid interpretation.
        self.exposure_count[~self.analysable_mask] = 0

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def empty(
        cls,
        *,
        sof_id: str,
        viewpoint_configuration: ViewpointConfiguration,
        environment: Environment,
        domain: AnalysisDomain,
        visibility_configuration: VisibilityConfiguration,
        exposure_dtype: np.dtype | type = np.uint32,
        metadata: dict[str, Any] | None = None,
    ) -> "SurveyObservabilityField":
        """Create an empty SOF for a specified analysis definition.

        No viewsheds are calculated by this constructor.

        The returned field contains zero exposure everywhere and can be
        populated incrementally using ``add_visibility`` or
        ``add_from_store``.
        """

        if not isinstance(
            viewpoint_configuration,
            ViewpointConfiguration,
        ):
            raise TypeError(
                "viewpoint_configuration must be a "
                "ViewpointConfiguration."
            )

        if not isinstance(environment, Environment):
            raise TypeError(
                "environment must be an Environment."
            )

        if not isinstance(domain, AnalysisDomain):
            raise TypeError(
                "domain must be an AnalysisDomain."
            )

        if not isinstance(
            visibility_configuration,
            VisibilityConfiguration,
        ):
            raise TypeError(
                "visibility_configuration must be a "
                "VisibilityConfiguration."
            )

        analysable = domain.analysable_mask

        if analysable is None:
            analysable = np.ones(
                domain.grid.shape,
                dtype=bool,
            )
        else:
            analysable = analysable.astype(
                bool,
                copy=True,
            )

        dtype = np.dtype(exposure_dtype)

        if not np.issubdtype(
            dtype,
            np.unsignedinteger,
        ):
            raise TypeError(
                "exposure_dtype must be an unsigned integer dtype."
            )

        exposure = np.zeros(
            domain.grid.shape,
            dtype=dtype,
        )

        return cls(
            sof_id=sof_id,
            viewpoint_configuration_id=(
                viewpoint_configuration.configuration_id
            ),
            environment_id=environment.environment_id,
            analysis_domain_id=domain.domain_id,
            visibility_configuration_id=(
                visibility_configuration.configuration_id
            ),
            sampling_unit=visibility_configuration.sampling_unit,
            exposure_count=exposure,
            analysable_mask=analysable,
            transform=domain.grid.transform,
            crs=domain.grid.crs,
            active_keys=[],
            metadata={} if metadata is None else dict(metadata),
        )

    # ------------------------------------------------------------------
    # Derived spatial products
    # ------------------------------------------------------------------

    @property
    def observable_mask(self) -> np.ndarray:
        """Return analysable cells visible from at least one active unit."""

        return (
            self.analysable_mask
            & (self.exposure_count > 0)
        )

    @property
    def blindspot_mask(self) -> np.ndarray:
        """Return analysable cells with no observation opportunity.

        The definition is:

            blind spot = analysable AND NOT observable

        Cells outside the domain or without valid environmental information
        are therefore not classified as blind spots.
        """

        return (
            self.analysable_mask
            & (self.exposure_count == 0)
        )

    @property
    def normalized_exposure(self) -> np.ndarray:
        """Return globally normalized exposure.

        The current calculation is:

            exposure_count / number_of_active_sampling_units

        This is an initial global normalization. It should not yet be
        interpreted as the final exposure-normalized sampling-effort metric.

        Future Rivelero versions may use cell-specific eligible observation
        opportunities as the denominator.
        """

        return normalize_exposure_global(
            self.exposure_count,
            self.n_active_units,
            analysable_mask=self.analysable_mask,
        )

    # ------------------------------------------------------------------
    # Summary properties
    # ------------------------------------------------------------------

    @property
    def n_active_units(self) -> int:
        """Number of visibility contributions currently active."""

        return len(self.active_keys)

    @property
    def n_analysable_cells(self) -> int:
        """Number of analysable raster cells."""

        return int(
            np.count_nonzero(self.analysable_mask)
        )

    @property
    def n_observable_cells(self) -> int:
        """Number of analysable cells visible at least once."""

        return int(
            np.count_nonzero(self.observable_mask)
        )

    @property
    def n_blindspot_cells(self) -> int:
        """Number of analysable cells visible from no active unit."""

        return int(
            np.count_nonzero(self.blindspot_mask)
        )

    # ------------------------------------------------------------------
    # Incremental SOF modification
    # ------------------------------------------------------------------

    def add_visibility(
        self,
        visibility: StoredVisibility,
    ) -> None:
        """Add one visibility contribution to the SOF.

        Exposure mathematics are delegated to
        ``observability.exposure.add_visibility_to_exposure``.

        Raises
        ------
        ValueError
            If the visibility result is already active or is incompatible
            with this SOF.
        """

        if not isinstance(visibility, StoredVisibility):
            raise TypeError(
                "visibility must be a StoredVisibility."
            )

        self._validate_visibility_compatibility(
            visibility,
        )

        if self.has_key(visibility.key):
            raise ValueError(
                "This visibility contribution is already active "
                "in the SOF."
            )

        add_visibility_to_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=self.analysable_mask,
            inplace=True,
        )

        self.active_keys.append(
            visibility.key
        )

    def remove_visibility(
        self,
        visibility: StoredVisibility,
    ) -> None:
        """Remove one visibility contribution from the SOF."""

        if not isinstance(visibility, StoredVisibility):
            raise TypeError(
                "visibility must be a StoredVisibility."
            )

        self._validate_visibility_compatibility(
            visibility,
        )

        if not self.has_key(visibility.key):
            raise KeyError(
                "This visibility contribution is not active "
                "in the SOF."
            )

        remove_visibility_from_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=self.analysable_mask,
            inplace=True,
        )

        self.active_keys.remove(
            visibility.key
        )

    def add_from_store(
        self,
        *,
        key: VisibilityKey,
        store: VisibilityStore,
    ) -> None:
        """Load an existing visibility result from the store and add it."""

        if not isinstance(store, VisibilityStore):
            raise TypeError(
                "store must be a VisibilityStore."
            )

        visibility = store.get(key)

        if visibility is None:
            raise KeyError(
                "Requested visibility is not present in the "
                "VisibilityStore."
            )

        self.add_visibility(
            visibility
        )

    def remove_from_store(
        self,
        *,
        key: VisibilityKey,
        store: VisibilityStore,
    ) -> None:
        """Load an active visibility result and remove its contribution."""

        if not isinstance(store, VisibilityStore):
            raise TypeError(
                "store must be a VisibilityStore."
            )

        visibility = store.get(key)

        if visibility is None:
            raise KeyError(
                "Requested visibility is not present in the "
                "VisibilityStore."
            )

        self.remove_visibility(
            visibility
        )

    def add_many(
        self,
        visibilities: Iterable[StoredVisibility],
    ) -> None:
        """Add several visibility contributions sequentially."""

        for visibility in visibilities:
            self.add_visibility(
                visibility
            )

    # ------------------------------------------------------------------
    # Membership
    # ------------------------------------------------------------------

    def has_key(
        self,
        key: VisibilityKey,
    ) -> bool:
        """Return whether a visibility contribution is currently active."""

        return key in self.active_keys

    @property
    def active_sampling_unit_ids(self) -> tuple[str, ...]:
        """Return identifiers of active sampling units."""

        return tuple(
            key.sampling_unit_id
            for key in self.active_keys
        )

    @property
    def active_viewpoint_ids(self) -> tuple[str, ...]:
        """Return Viewpoint IDs currently contributing to the SOF.

        In event-based analyses, a Viewpoint ID may occur more than once
        because multiple ObservationEvents can reference the same Viewpoint.
        """

        return tuple(
            key.viewpoint_id
            for key in self.active_keys
        )

    # ------------------------------------------------------------------
    # Counterfactual exposure
    # ------------------------------------------------------------------

    def exposure_if_added(
        self,
        visibility: StoredVisibility,
    ) -> np.ndarray:
        """Return exposure resulting from a hypothetical addition.

        The current SOF is not modified.
        """

        self._validate_visibility_compatibility(
            visibility,
        )

        if self.has_key(visibility.key):
            raise ValueError(
                "Visibility is already active in the SOF."
            )

        return add_visibility_to_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=self.analysable_mask,
            inplace=False,
        )

    def exposure_if_removed(
        self,
        visibility: StoredVisibility,
    ) -> np.ndarray:
        """Return exposure resulting from a hypothetical removal.

        The current SOF is not modified.
        """

        self._validate_visibility_compatibility(
            visibility,
        )

        if not self.has_key(visibility.key):
            raise KeyError(
                "Visibility is not active in the SOF."
            )

        return remove_visibility_from_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=self.analysable_mask,
            inplace=False,
        )

    # ------------------------------------------------------------------
    # Reset / copy
    # ------------------------------------------------------------------

    def clear(self) -> None:
        """Remove all visibility contributions from the SOF."""

        self.exposure_count.fill(0)
        self.active_keys.clear()

    def copy(
        self,
        *,
        sof_id: str | None = None,
    ) -> "SurveyObservabilityField":
        """Return an independent copy of the current SOF state."""

        return SurveyObservabilityField(
            sof_id=(
                self.sof_id
                if sof_id is None
                else sof_id
            ),
            viewpoint_configuration_id=(
                self.viewpoint_configuration_id
            ),
            environment_id=self.environment_id,
            analysis_domain_id=self.analysis_domain_id,
            visibility_configuration_id=(
                self.visibility_configuration_id
            ),
            sampling_unit=self.sampling_unit,
            exposure_count=self.exposure_count.copy(),
            analysable_mask=self.analysable_mask.copy(),
            transform=self.transform,
            crs=self.crs,
            active_keys=list(self.active_keys),
            created_at=datetime.now(timezone.utc),
            metadata=dict(self.metadata),
        )

    # ------------------------------------------------------------------
    # Internal validation
    # ------------------------------------------------------------------

    def _validate_active_keys(self) -> None:
        """Validate active visibility identities."""

        seen: set[VisibilityKey] = set()

        for key in self.active_keys:
            if not isinstance(
                key,
                VisibilityKey,
            ):
                raise TypeError(
                    "Every active_keys item must be a VisibilityKey."
                )

            if key in seen:
                raise ValueError(
                    "active_keys contains a duplicate VisibilityKey."
                )

            self._validate_key_compatibility(
                key
            )

            seen.add(key)

    def _validate_key_compatibility(
        self,
        key: VisibilityKey,
    ) -> None:
        """Ensure a VisibilityKey belongs to this analysis."""

        if key.environment_id != self.environment_id:
            raise ValueError(
                "VisibilityKey environment_id does not match SOF."
            )

        if (
            key.analysis_domain_id
            != self.analysis_domain_id
        ):
            raise ValueError(
                "VisibilityKey analysis_domain_id does not match SOF."
            )

        if (
            key.visibility_configuration_id
            != self.visibility_configuration_id
        ):
            raise ValueError(
                "VisibilityKey visibility_configuration_id "
                "does not match SOF."
            )

        expected_type = self.sampling_unit.value

        if key.sampling_unit_type != expected_type:
            raise ValueError(
                "VisibilityKey sampling_unit_type does not match "
                f"SOF sampling unit {expected_type!r}."
            )

    def _validate_visibility_compatibility(
        self,
        visibility: StoredVisibility,
    ) -> None:
        """Ensure stored visibility can legitimately modify this SOF."""

        self._validate_key_compatibility(
            visibility.key
        )

        if (
            visibility.shape
            != self.exposure_count.shape
        ):
            raise ValueError(
                "Stored visibility shape does not match SOF."
            )

        if visibility.transform != self.transform:
            raise ValueError(
                "Stored visibility transform does not match SOF."
            )

        if visibility.crs != self.crs:
            raise ValueError(
                "Stored visibility CRS does not match SOF."
            )

    # ------------------------------------------------------------------
    # Validation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _required_string(
        name: str,
        value: str,
    ) -> str:
        if not isinstance(value, str):
            raise TypeError(
                f"{name} must be a string."
            )

        result = value.strip()

        if not result:
            raise ValueError(
                f"{name} must be a non-empty string."
            )

        return result