"""Survey Observability Field for Rivelero.

A SurveyObservabilityField (SOF) represents the collective spatial
observation opportunity generated by a specified ViewpointConfiguration
within an Environment and AnalysisDomain under a VisibilityConfiguration.

The SOF preserves analysis_mask and valid_mask separately so that Rivelero
can distinguish outside-domain cells, invalid/unanalysable cells, genuine
blind spots, and observable cells.

Individual viewpoint/event visibility relationships are managed by
VisibilityStore rather than stored directly in the SOF. Exposure mathematics
are delegated to rivelero.observability.exposure, and spatial-state
classification is delegated to rivelero.observability.masks.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterable

import numpy as np
from affine import Affine
from rasterio.crs import CRS



from rivelero.core.configuration import ViewpointConfiguration
from rivelero.core.domain import AnalysisDomain
from rivelero.core.environment import Environment
from rivelero.observability.exposure import (
    add_visibility_to_exposure,
    maximum_exposure as calculate_maximum_exposure,
    normalize_exposure_global,
    remove_visibility_from_exposure,
)
from rivelero.observability.masks import (
    ObservabilityState,
    blindspot_mask as calculate_blindspot_mask,
    calculate_analysable_mask,
    observability_state as calculate_observability_state,
    observable_mask as calculate_observable_mask,
)
from rivelero.observability.storage import (
    StoredVisibility,
    VisibilityKey,
    VisibilityStore,
)
from rivelero.visibility.configuration import (
    SamplingUnit,
    VisibilityConfiguration,
)


@dataclass(slots=True)
class SurveyObservabilityField:
    """Collective observability generated by one survey configuration.

    The SOF stores analysis_mask and valid_mask separately.

    analysable_mask is derived as::

        analysis_mask & valid_mask

    Individual visibility masks remain in VisibilityStore.
    """

    sof_id: str

    viewpoint_configuration_id: str
    environment_id: str
    analysis_domain_id: str
    visibility_configuration_id: str

    sampling_unit: SamplingUnit | str

    exposure_count: np.ndarray
    analysis_mask: np.ndarray
    valid_mask: np.ndarray

    transform: Affine
    crs: CRS

    active_keys: list[VisibilityKey] = field(default_factory=list)

    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate and normalize SOF state."""

        self.sof_id = self._required_string(
            "sof_id",
            self.sof_id,
        )

        for name in (
            "viewpoint_configuration_id",
            "environment_id",
            "analysis_domain_id",
            "visibility_configuration_id",
        ):
            setattr(
                self,
                name,
                self._required_string(
                    name,
                    getattr(self, name),
                ),
            )

        if isinstance(self.sampling_unit, str):
            try:
                self.sampling_unit = SamplingUnit(
                    self.sampling_unit.strip().lower()
                )
            except ValueError as exc:
                raise ValueError(
                    "sampling_unit must be 'viewpoint' or "
                    "'observation_event'."
                ) from exc

        elif not isinstance(
            self.sampling_unit,
            SamplingUnit,
        ):
            raise TypeError(
                "sampling_unit must be a SamplingUnit or string."
            )

        # --------------------------------------------------------------
        # Exposure
        # --------------------------------------------------------------

        if not isinstance(
            self.exposure_count,
            np.ndarray,
        ):
            raise TypeError(
                "exposure_count must be a numpy.ndarray."
            )

        if self.exposure_count.ndim != 2:
            raise ValueError(
                "exposure_count must be two-dimensional."
            )

        if not np.issubdtype(
            self.exposure_count.dtype,
            np.integer,
        ):
            raise TypeError(
                "exposure_count must use an integer dtype."
            )

        if np.any(
            self.exposure_count < 0
        ):
            raise ValueError(
                "exposure_count cannot contain negative values."
            )

        # --------------------------------------------------------------
        # Analysis and validity masks
        # --------------------------------------------------------------

        for name in (
            "analysis_mask",
            "valid_mask",
        ):
            mask = getattr(
                self,
                name,
            )

            if not isinstance(
                mask,
                np.ndarray,
            ):
                raise TypeError(
                    f"{name} must be a numpy.ndarray."
                )

            if mask.ndim != 2:
                raise ValueError(
                    f"{name} must be two-dimensional."
                )

            mask = mask.astype(
                bool,
                copy=False,
            )

            if (
                mask.shape
                != self.exposure_count.shape
            ):
                raise ValueError(
                    f"{name} and exposure_count must "
                    "have the same shape."
                )

            setattr(
                self,
                name,
                mask,
            )

        # --------------------------------------------------------------
        # Spatial metadata
        # --------------------------------------------------------------

        if not isinstance(
            self.transform,
            Affine,
        ):
            raise TypeError(
                "transform must be an Affine."
            )

        if not isinstance(
            self.crs,
            CRS,
        ):
            self.crs = CRS.from_user_input(
                self.crs
            )

        # --------------------------------------------------------------
        # Active visibility keys
        # --------------------------------------------------------------

        if not isinstance(
            self.active_keys,
            list,
        ):
            self.active_keys = list(
                self.active_keys
            )

        self._validate_active_keys()

        # --------------------------------------------------------------
        # Other metadata
        # --------------------------------------------------------------

        if not isinstance(
            self.created_at,
            datetime,
        ):
            raise TypeError(
                "created_at must be a datetime object."
            )

        if not isinstance(
            self.metadata,
            dict,
        ):
            raise TypeError(
                "metadata must be a dictionary."
            )

        # Exposure outside analysable space has no valid interpretation.
        self.exposure_count[
            ~self.analysable_mask
        ] = 0

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def empty(
        cls,
        *,
        sof_id: str,
        viewpoint_configuration: ViewpointConfiguration,
        environment: Environment,
        domain: AnalysisDomain,
        visibility_configuration: VisibilityConfiguration,
        exposure_dtype: np.dtype | type = np.uint32,
        metadata: dict[str, Any] | None = None,
    ) -> "SurveyObservabilityField":
        """Create an empty SOF for a specified analysis definition.

        No viewsheds are calculated by this constructor.
        """

        if not isinstance(
            viewpoint_configuration,
            ViewpointConfiguration,
        ):
            raise TypeError(
                "viewpoint_configuration must be a "
                "ViewpointConfiguration."
            )

        if not isinstance(
            environment,
            Environment,
        ):
            raise TypeError(
                "environment must be an Environment."
            )

        if not isinstance(
            domain,
            AnalysisDomain,
        ):
            raise TypeError(
                "domain must be an AnalysisDomain."
            )

        if not isinstance(
            visibility_configuration,
            VisibilityConfiguration,
        ):
            raise TypeError(
                "visibility_configuration must be a "
                "VisibilityConfiguration."
            )

        # Preserve the two components of analysable space separately.
        analysis = (
            domain.effective_analysis_mask
        )

        valid = (
            domain.effective_valid_mask
        )

        dtype = np.dtype(
            exposure_dtype
        )

        if not np.issubdtype(
            dtype,
            np.unsignedinteger,
        ):
            raise TypeError(
                "exposure_dtype must be an unsigned integer dtype."
            )

        exposure = np.zeros(
            domain.grid.shape,
            dtype=dtype,
        )

        return cls(
            sof_id=sof_id,
            viewpoint_configuration_id=(
                viewpoint_configuration.configuration_id
            ),
            environment_id=(
                environment.environment_id
            ),
            analysis_domain_id=(
                domain.domain_id
            ),
            visibility_configuration_id=(
                visibility_configuration.configuration_id
            ),
            sampling_unit=(
                visibility_configuration.sampling_unit
            ),
            exposure_count=exposure,
            analysis_mask=analysis,
            valid_mask=valid,
            transform=domain.grid.transform,
            crs=domain.grid.crs,
            active_keys=[],
            metadata=(
                {}
                if metadata is None
                else dict(metadata)
            ),
        )

    # ------------------------------------------------------------------
    # Derived spatial products
    # ------------------------------------------------------------------

    @property
    def analysable_mask(
        self,
    ) -> np.ndarray:
        """Return cells that are both inside the domain and valid."""

        return calculate_analysable_mask(
            self.analysis_mask,
            self.valid_mask,
        )

    @property
    def observable_mask(
        self,
    ) -> np.ndarray:
        """Return analysable cells visible from at least one active unit."""

        return calculate_observable_mask(
            self.exposure_count,
            analysable=self.analysable_mask,
        )

    @property
    def blindspot_mask(
        self,
    ) -> np.ndarray:
        """Return analysable cells with no observation opportunity."""

        return calculate_blindspot_mask(
            self.exposure_count,
            analysable=self.analysable_mask,
        )

    @property
    def observability_state(
        self,
    ) -> np.ndarray:
        """Return categorical observability state.

        States
        ------
        0
            Outside analysis domain.
        1
            Invalid / unanalysable.
        2
            Blind spot.
        3
            Observable.
        """

        return calculate_observability_state(
            analysis_mask=self.analysis_mask,
            valid_mask=self.valid_mask,
            exposure_count=self.exposure_count,
        )

    @property
    def normalized_exposure(
        self,
    ) -> np.ndarray:
        """Return globally normalized exposure.

        This initial normalization divides exposure_count by the number
        of active sampling units.
        """

        return normalize_exposure_global(
            self.exposure_count,
            self.n_active_units,
            analysable_mask=self.analysable_mask,
        )

    # ------------------------------------------------------------------
    # Summary properties
    # ------------------------------------------------------------------

    @property
    def n_active_units(
        self,
    ) -> int:
        """Number of active visibility contributions."""

        return len(
            self.active_keys
        )

    @property
    def n_analysable_cells(
        self,
    ) -> int:
        """Number of analysable raster cells."""

        return int(
            np.count_nonzero(
                self.analysable_mask
            )
        )

    @property
    def n_observable_cells(
        self,
    ) -> int:
        """Number of analysable cells visible at least once."""

        return int(
            np.count_nonzero(
                self.observable_mask
            )
        )

    @property
    def n_blindspot_cells(
        self,
    ) -> int:
        """Number of analysable cells with no visibility."""

        return int(
            np.count_nonzero(
                self.blindspot_mask
            )
        )

    @property
    def maximum_exposure(
        self,
    ) -> int:
        """Largest exposure count among analysable cells."""

        return calculate_maximum_exposure(
            self.exposure_count,
            analysable_mask=self.analysable_mask,
        )

    def state_counts(
        self,
    ) -> dict[ObservabilityState, int]:
        """Return the number of cells in each categorical state."""

        counts = np.bincount(
            self.observability_state.ravel(),
            minlength=len(ObservabilityState),
        )

        return {
            state: int(counts[state])
            for state in ObservabilityState
        }

    # ------------------------------------------------------------------
    # Incremental SOF modification
    # ------------------------------------------------------------------

    def add_visibility(
        self,
        visibility: StoredVisibility,
    ) -> None:
        """Add one visibility contribution to the SOF."""

        if not isinstance(
            visibility,
            StoredVisibility,
        ):
            raise TypeError(
                "visibility must be a StoredVisibility."
            )

        self._validate_visibility_compatibility(
            visibility
        )

        if self.has_key(
            visibility.key
        ):
            raise ValueError(
                "This visibility contribution is already "
                "active in the SOF."
            )

        add_visibility_to_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=(
                self.analysable_mask
            ),
            inplace=True,
        )

        self.active_keys.append(
            visibility.key
        )

    def remove_visibility(
        self,
        visibility: StoredVisibility,
    ) -> None:
        """Remove one visibility contribution from the SOF."""

        if not isinstance(
            visibility,
            StoredVisibility,
        ):
            raise TypeError(
                "visibility must be a StoredVisibility."
            )

        self._validate_visibility_compatibility(
            visibility
        )

        if not self.has_key(
            visibility.key
        ):
            raise KeyError(
                "This visibility contribution is not "
                "active in the SOF."
            )

        remove_visibility_from_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=(
                self.analysable_mask
            ),
            inplace=True,
        )

        self.active_keys.remove(
            visibility.key
        )

    def add_from_store(
        self,
        *,
        key: VisibilityKey,
        store: VisibilityStore,
    ) -> None:
        """Load an existing visibility result from the store and add it."""

        if not isinstance(
            store,
            VisibilityStore,
        ):
            raise TypeError(
                "store must be a VisibilityStore."
            )

        visibility = store.get(
            key
        )

        if visibility is None:
            raise KeyError(
                "Requested visibility is not present in "
                "the VisibilityStore."
            )

        self.add_visibility(
            visibility
        )

    def remove_from_store(
        self,
        *,
        key: VisibilityKey,
        store: VisibilityStore,
    ) -> None:
        """Load an active visibility result and remove it."""

        if not isinstance(
            store,
            VisibilityStore,
        ):
            raise TypeError(
                "store must be a VisibilityStore."
            )

        visibility = store.get(
            key
        )

        if visibility is None:
            raise KeyError(
                "Requested visibility is not present in "
                "the VisibilityStore."
            )

        self.remove_visibility(
            visibility
        )

    def add_many(
        self,
        visibilities: Iterable[StoredVisibility],
    ) -> None:
        """Add several visibility contributions sequentially."""

        for visibility in visibilities:
            self.add_visibility(
                visibility
            )

    # ------------------------------------------------------------------
    # Membership
    # ------------------------------------------------------------------

    def has_key(
        self,
        key: VisibilityKey,
    ) -> bool:
        """Return whether a visibility contribution is active."""

        return key in self.active_keys

    @property
    def active_sampling_unit_ids(
        self,
    ) -> tuple[str, ...]:
        """Return identifiers of active sampling units."""

        return tuple(
            key.sampling_unit_id
            for key in self.active_keys
        )

    @property
    def active_viewpoint_ids(
        self,
    ) -> tuple[str, ...]:
        """Return Viewpoint IDs contributing to the SOF.

        In event-based analyses, a Viewpoint ID may occur more than once.
        """

        return tuple(
            key.viewpoint_id
            for key in self.active_keys
        )

    # ------------------------------------------------------------------
    # Counterfactual exposure
    # ------------------------------------------------------------------

    def exposure_if_added(
        self,
        visibility: StoredVisibility,
    ) -> np.ndarray:
        """Return exposure after a hypothetical addition.

        The SOF itself is not modified.
        """

        self._validate_visibility_compatibility(
            visibility
        )

        if self.has_key(
            visibility.key
        ):
            raise ValueError(
                "Visibility is already active in the SOF."
            )

        return add_visibility_to_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=(
                self.analysable_mask
            ),
            inplace=False,
        )

    def exposure_if_removed(
        self,
        visibility: StoredVisibility,
    ) -> np.ndarray:
        """Return exposure after a hypothetical removal.

        The SOF itself is not modified.
        """

        self._validate_visibility_compatibility(
            visibility
        )

        if not self.has_key(
            visibility.key
        ):
            raise KeyError(
                "Visibility is not active in the SOF."
            )

        return remove_visibility_from_exposure(
            self.exposure_count,
            visibility.visibility_mask,
            analysable_mask=(
                self.analysable_mask
            ),
            inplace=False,
        )

    # ------------------------------------------------------------------
    # Reset / copy
    # ------------------------------------------------------------------

    def clear(
        self,
    ) -> None:
        """Remove all visibility contributions from the SOF."""

        self.exposure_count.fill(
            0
        )

        self.active_keys.clear()

    def copy(
        self,
        *,
        sof_id: str | None = None,
    ) -> "SurveyObservabilityField":
        """Return an independent copy of the current SOF."""

        return SurveyObservabilityField(
            sof_id=(
                self.sof_id
                if sof_id is None
                else sof_id
            ),
            viewpoint_configuration_id=(
                self.viewpoint_configuration_id
            ),
            environment_id=(
                self.environment_id
            ),
            analysis_domain_id=(
                self.analysis_domain_id
            ),
            visibility_configuration_id=(
                self.visibility_configuration_id
            ),
            sampling_unit=(
                self.sampling_unit
            ),
            exposure_count=(
                self.exposure_count.copy()
            ),
            analysis_mask=(
                self.analysis_mask.copy()
            ),
            valid_mask=(
                self.valid_mask.copy()
            ),
            transform=(
                self.transform
            ),
            crs=(
                self.crs
            ),
            active_keys=list(
                self.active_keys
            ),
            created_at=datetime.now(
                timezone.utc
            ),
            metadata=dict(
                self.metadata
            ),
        )

    # ------------------------------------------------------------------
    # Internal validation
    # ------------------------------------------------------------------

    def _validate_active_keys(
        self,
    ) -> None:
        """Validate active visibility identities."""

        seen: set[
            VisibilityKey
        ] = set()

        for key in self.active_keys:

            if not isinstance(
                key,
                VisibilityKey,
            ):
                raise TypeError(
                    "Every active_keys item must be "
                    "a VisibilityKey."
                )

            if key in seen:
                raise ValueError(
                    "active_keys contains a duplicate "
                    "VisibilityKey."
                )

            self._validate_key_compatibility(
                key
            )

            seen.add(
                key
            )

    def _validate_key_compatibility(
        self,
        key: VisibilityKey,
    ) -> None:
        """Ensure a VisibilityKey belongs to this analysis."""

        if (
            key.environment_id
            != self.environment_id
        ):
            raise ValueError(
                "VisibilityKey environment_id "
                "does not match SOF."
            )

        if (
            key.analysis_domain_id
            != self.analysis_domain_id
        ):
            raise ValueError(
                "VisibilityKey analysis_domain_id "
                "does not match SOF."
            )

        if (
            key.visibility_configuration_id
            != self.visibility_configuration_id
        ):
            raise ValueError(
                "VisibilityKey visibility_configuration_id "
                "does not match SOF."
            )

        expected_type = (
            self.sampling_unit.value
        )

        if (
            key.sampling_unit_type
            != expected_type
        ):
            raise ValueError(
                "VisibilityKey sampling_unit_type "
                "does not match SOF sampling unit "
                f"{expected_type!r}."
            )

    def _validate_visibility_compatibility(
        self,
        visibility: StoredVisibility,
    ) -> None:
        """Ensure stored visibility can modify this SOF."""

        self._validate_key_compatibility(
            visibility.key
        )

        if (
            visibility.shape
            != self.exposure_count.shape
        ):
            raise ValueError(
                "Stored visibility shape does not match SOF."
            )

        if (
            visibility.transform
            != self.transform
        ):
            raise ValueError(
                "Stored visibility transform does not match SOF."
            )

        if (
            visibility.crs
            != self.crs
        ):
            raise ValueError(
                "Stored visibility CRS does not match SOF."
            )

    # ------------------------------------------------------------------
    # Validation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _required_string(
        name: str,
        value: str,
    ) -> str:
        """Validate a required non-empty string."""

        if not isinstance(
            value,
            str,
        ):
            raise TypeError(
                f"{name} must be a string."
            )

        result = value.strip()

        if not result:
            raise ValueError(
                f"{name} must be a non-empty string."
            )

        return result